export const MusicFiles = [ {name:"Test", fileName: "data/xml/test.musicxml"},
  {name:"A Thousand Miles", fileName: "data/xml/A_Thousand_Miles.musicxml"},
  {name:"Albeniz - Asturias Suite Espaola No. 1", fileName: "data/xml/Albeniz - Asturias Suite Espaola No. 1.musicxml"},
  {name:"Amnesia A Machine For Pigs - Mandus", fileName: "data/xml/Amnesia A Machine For Pigs - Mandus.musicxml"},
  {name:"Arpeggio D major", fileName: "data/xml/Arpeggio D major.musicxml"},
  {name:"Arpeggio D minor", fileName: "data/xml/Arpeggio D minor.musicxml"},
  {name:"Arpeggio D minor broken", fileName: "data/xml/Arpeggio D minor broken.musicxml"},
  {name:"Arpeggio F major", fileName: "data/xml/Arpeggio F major.musicxml"},
  {name:"Arpeggio F major - octave", fileName: "data/xml/Arpeggio F major - octave.musicxml"},
  {name:"Arpeggio F major - octave + 3th", fileName: "data/xml/Arpeggio F major - octave + 3th.musicxml"},
  {name:"Arpeggio H minor", fileName: "data/xml/Arpeggio H minor.musicxml"},
  {name:"Bach G Minor arranged Luo Ni", fileName: "data/xml/Bach G Minor arranged Luo Ni.musicxml"},
  {name:"Beethoven Bagatelle No. 25 in A minor", fileName: "data/xml/Beethoven Bagatelle No. 25 in A minor.musicxml"},
  {name:"Blue dabune", fileName: "data/xml/Blue dabune.xml"},
  {name:"Beethoven Ode to Joy", fileName: "data/xml/Beethoven - Ode to Joy.musicxml"},
  {name:"Beethoven Sonate No. 2 2nd Movement", fileName: "data/xml/Beethoven - Sonate No. 2 2nd Movement.musicxml"},
  {name:"Beethoven Sonata No. 8 Op. 13 Pathetique", fileName: "data/xml/Beethoven Sonata No. 8 Op. 13 Pathetique.musicxml"},
  {name:"Beethoven Sonata No. 8 Op. 13 Pathetique - Second Ab major", fileName: "data/xml/Beethoven Sonata No. 8 Op. 13 Pathetique - Second Ab major.musicxml"},
  {name:"Beethoven Sonata No. 8 Op. 13 Pathetique III Rondo", fileName: "data/xml/Beethoven Sonata No. 8 Op. 13 Pathetique III Rondo.musicxml"},
  {name:"Beethoven Sonata 14 C# Minor", fileName: "data/xml/Beethoven Sonata 14 C Sharp Minor.musicxml"},
  {name:"Beethoven Sonata 14 C# Minor 2rd Movement", fileName: "data/xml/Beethoven Sonata 14 C Sharp Minor 2rd Movemen.musicxml"},
  {name:"Beethoven Sonata 14 C# Minor 3rd Movemen", fileName: "data/xml/Beethoven Sonata 14 C Sharp Minor 3rd Movemen.musicxml"},
  {name:"Beethoven Sonate 17 Tempest 3rd Movement", fileName: "data/xml/Beethoven Sonate No. 17 Tempest 3rd Movement.musicxml"},
  {name:"Beethoven Sonata 21 Op. 53", fileName: "data/xml/Beethoven Piano_Sonata_No.21_Op.53.musicxml"},
  {name:"Beethoven Sonata No. 23 Op. 57 Appassionata", fileName: "data/xml/Beethoven Sonata No. 23 Op. 57 Appassionata Complete.musicxml"},
  {name:"Beethoven Symphony No. 5 1 st movement Piano solo", fileName: "data/xml/Beethoven Symphony No. 5 1 st movement Piano solo.musicxml"},
  {name:"Beethoven - Symphony 7 II Allegretto", fileName: "data/xml/Beethoven - Symphony 7 II Allegretto.musicxml"},
  {name:"Brahms Op. 35 Variations on a Theme Paganini", fileName: "data/xml/Brahms Op. 35 Variations on a Theme Paganini.musicxml"},
  {name:"Burgmuller - Op.100 - Arabesque", fileName: "data/xml/Burgmuller - Op.100 - Arabesque.musicxml"},
  // {name:"Beethoven Op. 53", fileName: "data/xml/Beethoven-Op._53.xml"},
  // {name:"BWV Praeambulum in F Major", fileName: "data/xml/BWV Praeambulum in F Major.xml"},
  // {name:"BWV 846 Harmony", fileName: "data/xml/BWV-846-Harmony.xml"},
  // {name:"B Major", fileName: "data/xml/B major.musicxml"},
  // {name:"BWV 855 Prelude E Minor", fileName: "data/xml/BWV-855_in_E_Minor.musicxml"},
  // {name:"BWV-847 C minor Harmony", fileName: "data/xml/BWV-847 C minor Harmony.musicxml"},
  // {name:"BWV-847 Harmony", fileName: "data/xml/BWV-847_Harmony.musicxml"},
  // {name:"By the Seaside", fileName: "data/xml/By the Seaside.musicxml"},
  // {name:"C major double time II", fileName: "data/xml/C major double time II.musicxml"},
  // {name:"C major double time", fileName: "data/xml/C major double time.musicxml"},
  // {name:"Cherny Op. 453-3", fileName: "data/xml/Cherny-Op._453-3.xml"},
  // {name:"Cherny Op. 453-4", fileName: "data/xml/Cherny-Op._453-4.xml"},
  // {name:"Cherny Op. 453-5", fileName: "data/xml/Cherny-Op._453-5.xml"},
  // {name:"Cherny Op. 453-6", fileName: "data/xml/Cherny-Op._453-6.xml"},
  // {name:"Cherny Op. 453-6-left", fileName: "data/xml/Cherny-Op._453-6-left.xml"},
  // {name:"Cherny Op. 453-7", fileName: "data/xml/Cherny-Op._453-7.xml"},
  // {name:"Cherny Op. 453-8", fileName: "data/xml/Cherny-Op._453-8.xml"},
  // {name:"Cherny Op. 453-9", fileName: "data/xml/Cherny-Op._453-9.xml"},
  // {name:"Cherny-17", fileName: "data/xml/Cherny-17.musicxml"},
  // {name:"D 935 Ab Major", fileName: "data/xml/D 935 Importu.musicxml"},
  // {name:"Gliere 43 №1", fileName: "data/xml/Gliere 43 №1.musicxml"},
  // {name:"Heller Sailor's Song", fileName: "data/xml/Heller - Sailor's Song op.musicxml"},
  {name:"Czerny- Op.718 - 17", fileName: "data/xml/Czerny- Op.718 - 17.musicxml"},
  {name:"A dur", fileName: "data/xml/A dur.musicxml"},
  {name:"Adagio in G minor (Giazotto Albinoni)", fileName: "data/xml/Adagio in G minor (Giazotto Albinoni).musicxml"},
  {name:"Aaron Zigman The Notebook Theme", fileName: "data/xml/Aaron Zigman The Notebook Theme.musicxml"},
  // {name:"BWV 1068 - Air on the G String", fileName: "data/xml/BWV 1068 - Air on the G String.musicxml"},
  {name:"Britney Spears - Everytime", fileName: "data/xml/Britney Spears - Everytime.musicxml"},
  {name:"Brahms - Lullaby easy", fileName: "data/xml/Brahms - Lullaby easy.musicxml"},
  {name:"Brahms - Hungarian Dance No.5 EASY version", fileName: "data/xml/Brahms - Hungarian Dance No.5 EASY version Flowkey.musicxml"},
  {name:"Brahms - Hungarian Dance No 5 in G Minor", fileName: "data/xml/Brahms - Hungarian Dance No 5 in G Minor.musicxml"},
  {name:"BWV Anh Menuet 2", fileName: "data/xml/BWV Anh Menuet 2.musicxml"},
  {name:"BWV Anh Menuet 3", fileName: "data/xml/BWV Anh Menuet 3.musicxml"},
  {name:"BWV Anh Menuet 4", fileName: "data/xml/BWV Anh Menuet 4.musicxml"},
  {name:"BWV Musette in D Anh. 126", fileName: "data/xml/BWV - Bach_Musette_in_D_Anh._126.musicxml"},
  {name:"BWV 528 Organ Sonata No4 2. Andante", fileName: "data/xml/BWV 528_Organ_Sonata_No._4_-_2._Andante_Adagio_-_Vikingur_Olafsson_Interpretation.musicxml"},
  //{name:"BWV 565 exercise", fileName: "data/xml/BWV-565 exercise.musicxml"},
  //{name:"BWV 565 second part", fileName: "data/xml/BWV 565 second part.musicxml"},
  {name:"BWV 543 Prelude A Minor", fileName: "data/xml/BWV 543 Prelude A Minor.musicxml"},
  {name:"BWV 565", fileName: "data/xml/BWV-565.musicxml"},
  {name:"BWV 578 - Bach Fugue in G Minor", fileName: "data/xml/BWV 578 - Bach Fugue in G Minor Piano solo.musicxml"},
  {name:"BWV 772 J. S. Bach Inventio 1", fileName: "data/xml/BWV 772 J._S._Bach_Invention_Nr._1.musicxml"},
  {name:"BWV 773 J. S. Bach Inventio 2", fileName: "data/xml/BWV 773 J.S.Bach_Inventio_2.musicxml"},
  {name:"BWV 830 Partita E minor", fileName: "data/xml/BWV 830 Partita E minor.musicxml"},
  {name:"BWV 846 Prelude C Major", fileName: "data/xml/BWV 846 Prelude C Major.xml"},
  {name:"BWV 847 ex001", fileName: "data/xml/BWV 847 ex001.musicxml"},
  {name:"BWV 847 Fugue in C Minor", fileName: "data/xml/BWV 847 Fugue in C Minor.musicxml"},
  {name:"BWV 847 Prelude C Minor", fileName: "data/xml/BWV 847 Prelude C Minor.musicxml"},
  {name:"BWV 848 Prelude C# Major", fileName: "data/xml/BWV 848 Prelude C Major.musicxml"},
  {name:"BWV 849 Fugue C# Minor", fileName: "data/xml/BWV 849 Fugue C Minor.musicxml"},
  {name:"BWV 849 Prelude C# Minor", fileName: "data/xml/BWV 849 Prelude C sharp Minor.musicxml"},
  {name:"BWV 850 Prelude D Major", fileName: "data/xml/BWV 850 Prelude D Major.musicxml"},
  {name:"BWV 851 Prelude D Minor", fileName: "data/xml/BWV 851 Prelude D Minor.musicxml"},
  {name:"BWV 853 Prelude N8 in E Flat Minor", fileName: "data/xml/BWV 853 Prelude N8 in E Flat Minor.musicxml"},
  {name:"BWV 855 Prelude E Minor", fileName: "data/xml/BWV 855 Prelude No. 10 in E Minor.musicxml"},
  {name:"BWV 855a Prelude B minor arr Siloti", fileName: "data/xml/BWV 855a Prelude_in_B_minor_arr._by_A_Siloti.musicxml"},
  {name:"BWV 858 Prelude F-sharp Major", fileName: "data/xml/BWV-858_Prelude_F_sharp_Major.xml"},
  {name:"BWV 867 Fugue No. 22 in B Minor", fileName: "data/xml/BWV 867 Fugue No. 22 in B Minor.musicxml"},
  {name:"BWV 867 Prelude No. 22 in B Minor", fileName: "data/xml/BWV 867 Prelude No. 22 in B Minor.musicxml"},
  {name:"BWV 927 (Twelve Little Preludes)", fileName: "data/xml/BWV 927.musicxml"},
  {name:"BWV 939 Prelude No. 2 in C Major", fileName: "data/xml/BWV 939 Prelude No. 2 in C Major.musicxml"},
  {name:"BWV 940 Prelude D minor", fileName: "data/xml/BWV 940 Prelude D minor.musicxml"},
  {name:"BWV 974 - Adagio Concerto D minor", fileName: "data/xml/BWV 974 - Adagio Concerto D minor.musicxml"},
  {name:"BWV 999 Little Preambule C Minor", fileName: "data/xml/BWV-999 Little Preambule C Minor.musicxml"},
  {name:"BWV 1004 Chaconne by Busoni-Bach", fileName: "data/xml/BWV 1004 Chaconne by Busoni-Bach.musicxml"},
  {name:"BWV 1052 Keyboard Concerto No. 1 in D minor", fileName: "data/xml/BWV 1052 Keyboard Concerto No. 1 in D minor.musicxml"},
  {name:"BWV 1067 Badinerie Orchestersuite N. 2 h-Moll", fileName: "data/xml/BWV 1067 J.S._Bach_Badinerie_aus_der_Orchestersuite_Nr_.2_h-Moll.musicxml"},
  {name:"BWV 1068 - Air on the G String", fileName: "data/xml/BWV 1068 J._S._Bach_-_Air_on_the_G_String_Piano_arrangement.musicxml"},
  {name:"BWV 1080 - Contrapunctus I", fileName: "data/xml/BWV 1080 Contrapunctus_I_-_The_Art_of_Fugue.musicxml"},
  {name:"Lonely shepherd", fileName: "data/xml/Lonely_shepherd_composed_by_James_Last.musicxml"},
  {name:"Canon D dur full", fileName: "data/xml/Canon_in_D_full.musicxml"},
  {name:"Canon D dur", fileName: "data/xml/Canon D dur.musicxml"},
  {name:"Carol of the Bells", fileName: "data/xml/Carol of the Bells.musicxml"},
  {name:"Cherny Op. 453-1", fileName: "data/xml/Cherny-Op._453-1.xml"},
  {name:"Cherny Op. 453-2", fileName: "data/xml/Cherny-Op._453-2.xml"},
  {name:"Chopin - Op. 64 No. 1", fileName: "data/xml/Chopin Op. 64 No. 1.musicxml"},
  {name:"Chopin - Op. 64 No. 2", fileName: "data/xml/Chopin Drei Walzer Op. 64 No. 2.musicxml"},
  {name:"Chopin - Op. 69 No. 2 in B Minor", fileName: "data/xml/Chopin op. 69 No. 2 in B Minor.musicxml"},
  {name:"Chopin - Fantaisie-Impromptu", fileName: "data/xml/Chopin - Fantaisie-Impromptu.musicxml"},
  {name:"Chopin - Nocturne in B-Flat minor, Op. 9, No. 1 ", fileName: "data/xml/Chopin_-_Nocturne_Op_9_No_1_B_Flat_Minor.musicxml"},
  {name:"Chopin - Nocturne in E-flat major, Op. 9, No. 2", fileName: "data/xml/Chopin_Nocture_opus_9_number2.musicxml"},
  {name:"Chopin - Nocturne in C sharp Minor", fileName: "data/xml/Chopin Nocturne in C sharp Minor.musicxml"},
  {name:"Chopin - Sonata No.2 in B-flat minor", fileName: "data/xml/Chopin Sonata_No.2_in_B-flat_minor.musicxml"},
  {name:"Chopin 10-2 in A Minor", fileName: "data/xml/Chopin 10-2.musicxml"},
  {name:"Chopin Etude Op. 10 No. 3 E Major Tristesse", fileName: "data/xml/Chopin Etude Op. 10 No. 3 E Major Tristesse.musicxml"},
  {name:"Chopin 25-11 in A Minor Winter Wind", fileName: "data/xml/Chopin 25-11 in A Minor Winter Wind.musicxml"},
  {name:"Chopin 28-2 in A Minor", fileName: "data/xml/Chopin 28-2 in A Minor.musicxml"},
  {name:"Chopin 28-4 in E Minor", fileName: "data/xml/Prelude_Opus_28_No._4_in_E_Minor.musicxml"},
  {name:"Chopin 28-14 in Eb Minor", fileName: "data/xml/Chopin 28-14 in Eb Minor.musicxml"},
  {name:"Chopin 28-15 in Db Major", fileName: "data/xml/Chopin 28-15 in Db Major.musicxml"},
  {name:"Chopin 28-20 in C Minor", fileName: "data/xml/Chopin 28-20 in C Minor.musicxml"},
  {name:"Chromatic - exercise", fileName: "data/xml/Chromatic - exercise.musicxml"},
  {name:"Chromatic Scale", fileName: "data/xml/Chromatic Scale.musicxml"},
  // {name:"Clint Mansell - Requiem For a Dream", fileName: "data/xml/Clint Mansell - Requiem For a Dream Pianistos.musicxml"},
  {name:"Clint Mansell - Requiem For a Dream", fileName: "data/xml/Clint Mansell - Requiem For a Dream Pianistos Eazy.musicxml"},
  {name:"Curb your Sheet Music Frolic", fileName: "data/xml/Curb_your_Sheet_Music_Frolic.musicxml"},
  {name:"Czerny - Op.139 - 001", fileName: "data/xml/Czerny- Op.139 - 001.musicxml"},
  {name:"Czerny - Op.139 - 002", fileName: "data/xml/Czerny- Op.139 - 002.musicxml"},
  {name:"Czerny - Op.139 - 003", fileName: "data/xml/Czerny- Op.139 - 003.musicxml"},
  {name:"Czerny - Op.139 - 004", fileName: "data/xml/Czerny- Op.139 - 004.musicxml"},
  {name:"Czerny - Op.139 - 005", fileName: "data/xml/Czerny- Op.139 - 005.musicxml"},
  {name:"Czerny - Op.139 - 006", fileName: "data/xml/Czerny- Op.139 - 006.musicxml"},
  {name:"Czerny - Op.139 - 007", fileName: "data/xml/Czerny- Op.139 - 007.musicxml"},
  {name:"Czerny - Op.139 - 008", fileName: "data/xml/Czerny- Op.139 - 008.musicxml"},
  {name:"Czerny - Op.139 - 009", fileName: "data/xml/Czerny- Op.139 - 009.musicxml"},
  {name:"Czerny - Op.139 - 010", fileName: "data/xml/Czerny- Op.139 - 010.musicxml"},
  {name:"Czerny - Op.139 - 011", fileName: "data/xml/Czerny- Op.139 - 011.musicxml"},
  {name:"Czerny - Op.139 - 012", fileName: "data/xml/Czerny- Op.139 - 012.musicxml"},
  {name:"Czerny - Op.139 - 013", fileName: "data/xml/Czerny- Op.139 - 013.musicxml"},
  {name:"Czerny - Op.139 - 014", fileName: "data/xml/Czerny- Op.139 - 014.musicxml"},
  {name:"Czerny - Op.139 - 015", fileName: "data/xml/Czerny- Op.139 - 015.musicxml"},
  {name:"Czerny - Op.139 - 016", fileName: "data/xml/Czerny- Op.139 - 016.musicxml"},
  {name:"Czerny - Op.139 - 017", fileName: "data/xml/Czerny- Op.139 - 017.musicxml"},
  {name:"Czerny - Op.139 - 018", fileName: "data/xml/Czerny- Op.139 - 018.musicxml"},
  {name:"Czerny - Op.139 - 019", fileName: "data/xml/Czerny- Op.139 - 019.musicxml"},
  {name:"Czerny - Op.139 - 020", fileName: "data/xml/Czerny- Op.139 - 020.musicxml"},
  {name:"Czerny - Op.139 - 021", fileName: "data/xml/Czerny- Op.139 - 021.musicxml"},
  {name:"Czerny - Op.139 - 022", fileName: "data/xml/Czerny- Op.139 - 022.musicxml"},
  {name:"Czerny - 50 little Studies 01", fileName: "data/xml/Czerny - 50 little Studies 01.musicxml"},
  {name:"Czerny - 50 little Studies 01 - 01", fileName: "data/xml/Czerny - 50 little Studies 01 - 01.musicxml"},
  {name:"Czerny - 50 little Studies 02", fileName: "data/xml/Czerny - 50 little Studies 02.musicxml"},
  {name:"Czerny - 50 little Studies 03", fileName: "data/xml/Czerny - 50 little Studies 03.musicxml"},
  {name:"Czerny - 50 little Studies 04", fileName: "data/xml/Czerny - 50 little Studies 04.musicxml"},
  {name:"Czerny - 50 little Studies 05", fileName: "data/xml/Czerny - 50 little Studies 05.musicxml"},
  {name:"Czerny - 50 little Studies 06", fileName: "data/xml/Czerny - 50 little Studies 06.musicxml"},
  {name:"Czerny - Germer-19", fileName: "data/xml/Czerny-Germer-19.musicxml"},
  {name:"Czerny - Op. 740 Etude in G minor no. 14", fileName: "data/xml/Czerny - Op. 740 Etude in G minor no. 14.musicxml"},
  {name:"Czerny - Op. 740 Etude in G minor no. 50", fileName: "data/xml/Czerny - Op. 740 Etude in G minor no. 50.musicxml"},
  {name:"Czerny - Op. 740 Etude in C major no. 1.musicxml", fileName: "data/xml/Czerny - Op. 740 Etude in C major no. 1.musicxml"},
  {name:"D dur 4 octave", fileName: "data/xml/D dur.musicxml"},
  {name:"Dance of the Knights", fileName: "data/xml/Dance_of_the_Knights_Transcription_for_solo_piano.musicxml"},
  {name:"Debussy Claude L.113 Le Coin des enfants - La neige danse Childrens Corner - The Snow Is Dancing", fileName: "data/xml/Debussy Claude L.113 Le Coin des enfants - La neige danse Childrens Corner - The Snow Is Dancing.musicxml"},
  {name:"Debussy - Clair de Lune Suite Bergamasque No. 3", fileName: "data/xml/Debussy - Clair de Lune Suite Bergamasque No. 3.musicxml"},
  {name:"Domenico Scarlatti K.466", fileName: "data/xml/Domenico Scarlatti K.466.musicxml"},
  {name:"Domenico Scarlatti K.466-E-F-G", fileName: "data/xml/Domenico Scarlatti K.466 - E-F-G.musicxml"},
  {name:"ex001", fileName: "data/xml/ex001.musicxml"},
  {name:"Ennio Morricone - Chi Mai", fileName: "data/xml/Ennio Morricone - Chi Mai.musicxml"},
  {name:"F dur", fileName: "data/xml/F dur.musicxml"},
  {name:"F Major diverge", fileName: "data/xml/F Major diverge.musicxml"},
  {name:"Faure - Sicilienne", fileName: "data/xml/Faure - Sicilienne.musicxml"},
  {name:"For the Damaged Coda", fileName: "data/xml/Evil_Morty_Theme_For_the_Damaged_Coda_Solo_Piano.musicxml"},
  {name:"G dur octave", fileName: "data/xml/G dur octave.musicxml"},
  {name:"G minor octave hand separate", fileName: "data/xml/G dur octave hand separate.musicxml"},
  {name:"Greensleeves.musicxml", fileName: "data/xml/Greensleeves.musicxml"},
  {name:"Game of Thrones", fileName: "data/xml/Game_of_Thrones_Main_Theme.musicxml"},
  {name:"Grieg - Op.43 Lyric Pieces No. 6 - To Spring", fileName: "data/xml/Grieg - Op.43 Lyric Pieces No. 6 - To Spring.musicxml"},
  {name:"Grieg - Op.57 No.6 - Hjemve Homesickness Nostalgia di casa", fileName: "data/xml/Grieg - Op.57 No.6 - Hjemve Homesickness Nostalgia di casa.musicxml"},
  {name:"Grieg - Op.71 Kobold", fileName: "data/xml/Grieg - Op.71 Kobold.musicxml"},
  {name:"Grieg - Piano Concerto in A minor - 1st movement", fileName: "data/xml/Grieg_-_Piano_Concerto_in_A_minor_-_1st_movement_-_Piano_Solo.musicxml"},
  {name:"Grieg In The Hall Of The Mountain King", fileName: "data/xml/Grieg In The Hall Of The Mountain King.musicxml"},
  {name:"Gymnopedie", fileName: "data/xml/Gymnopedie.musicxml"},
  {name:"Gnossienne No 1", fileName: "data/xml/Gnossienne_No._1.musicxml"},
  {name:"Hallelujah", fileName: "data/xml/Hallelujah__Leonard_Cohen_Rousseau_Cover.musicxml"},
  {name:"Halloran Dustin - Opus No. 17", fileName: "data/xml/Halloran Dustin - Opus No. 17.musicxml"},
  {name:"Halloran - The Lion theme", fileName: "data/xml/Halloran - The Lion theme.musicxml"},
  {name:"Handel - Passacaglia", fileName: "data/xml/Handel - Passacaglia.musicxml"},
  {name:"Handel - Suite no.7 HWV 432", fileName: "data/xml/Handel - Passacaglia_from_Suite_no.7_HWV_432_-_Georg_Frideric.musicxml"},
  {name:"Hanon - Ex 01", fileName: "data/xml/Hanon - Ex 01.musicxml"},
  {name:"Hanon - Ex 02", fileName: "data/xml/Hanon - Ex 02.musicxml"},
  {name:"Hanon - Ex 03", fileName: "data/xml/Hanon - Ex 03.musicxml"},
  {name:"Hanon - Ex 04", fileName: "data/xml/Hanon - Ex 04.musicxml"},
  {name:"Hanon - Ex 05", fileName: "data/xml/Hanon - Ex 05.musicxml"},
  {name:"Hanon - Ex 06", fileName: "data/xml/Hanon - Ex 06.musicxml"},
  {name:"Hanon - Ex 07", fileName: "data/xml/Hanon - Ex 07.musicxml"},
  {name:"Hanon - Ex 08", fileName: "data/xml/Hanon - Ex 08.musicxml"},
  {name:"Hanon - Ex 09", fileName: "data/xml/Hanon - Ex 09.musicxml"},
  {name:"Hanon - Ex 10", fileName: "data/xml/Hanon - Ex 10.musicxml"},
  {name:"Hanon - Ex 11", fileName: "data/xml/Hanon - Ex 11.musicxml"},
  {name:"Hanon - Ex 12", fileName: "data/xml/Hanon - Ex 12.musicxml"},
  {name:"Hanon - Ex 13", fileName: "data/xml/Hanon - Ex 13.musicxml"},
  {name:"Hanon - Ex 14", fileName: "data/xml/Hanon - Ex 14.musicxml"},
  {name:"Hanz Zimmer - Mountains", fileName: "data/xml/Hanz Zimmer - Mountains.musicxml"},
  {name:"Hanz Zimmer - Pirates of the Caribbean - Hes a Pirate", fileName: "data/xml/Hanz Zimmer - Pirates_of_the_Caribbean - Hes a Pirate.musicxml"},
  {name:"Happy Birthday To You Piano", fileName: "data/xml/Happy Birthday To You Piano.musicxml"},
  {name:"Heller - Opus 45 no 15 D minor", fileName: "data/xml/Etude_No._15_in_D_Minor_Opus_45_No._15_Heller.musicxml"},
  {name:"Heller exercise 1 ", fileName: "data/xml/Heller-exercise-1.musicxml"},
  {name:"Ilya Beshelvi - Wind", fileName: "data/xml/Ilya Beshelvi - Wind.musicxml"},
  {name:"Jingle Bells", fileName: "data/xml/Jingle_Bells.musicxml"},
  {name:"John Cage - In a Landscape", fileName: "data/xml/John Cage - In a Landscape.musicxml"},
  {name:"John Field - Nocturne No.5 - H.37 Edited by Liszt", fileName: "data/xml/John Field - Nocturne No.5 - H.37 Edited by Liszt.musicxml"},
  {name:"John Field - Nocturne No. 10 in E minor H 46", fileName: "data/xml/John Field - Nocturne No. 10 in E minor H 46.musicxml"},
  {name:"Joe Dassin - Et si tu nexistais pas", fileName: "data/xml/Joe Dassin - Et si tu nexistais pas.musicxml"},
  {name:"John Towner Williams - Hedwig's theme", fileName: "data/xml/John Towner Williams - Hedwig's theme.musicxml"},
  {name:"La Candeur", fileName: "data/xml/La Candeur.musicxml"},
  {name:"LE COUCOU by DAQUIN The Cuckoo", fileName: "data/xml/LE_COUCOU_by_DAQUIN_The_Cuckoo.musicxml"},
  {name:"Liszt S. 136 No.4", fileName: "data/xml/Liszt S. 136 No.4.musicxml"},
  {name:"Liszt S. 136 No.10", fileName: "data/xml/Liszt S. 136 No.10.musicxml"},
  {name:"Liszt - Etude in G Minor La Campanella S. 1413", fileName: "data/xml/Liszt - Etude_in_G_Minor_La_Campanella_S._1413-cuted.musicxml"},
  {name:"Love Theme from Flashdance", fileName: "data/xml/Love_Theme_from_Flashdance.musicxml"},
  // {name:"This Love", fileName: "data/xml/This Love.musicxml"},
  // {name:"Вариация Баха", fileName: "data/xml/Вариация Баха.musicxml"}, //Little Preambule C Major
  {name:"Lucifer - Creep", fileName: "data/xml/Lucifer - Creep.musicxml"},
  {name:"Ludovico Einaudi - Dietro Casa", fileName: "data/xml/Ludovico Einaudi - Dietro Casa.musicxml"},
  {name:"Ludovico Einaudi - Fly", fileName: "data/xml/Einaudi - Fly.musicxml"},
  {name:"Maksim Mrvica - Croatian Rhapsody", fileName: "data/xml/Maksim Mrvica - Croatian Rhapsody.musicxml"},
  {name:"Max Richter - The Departure The Leftovers score", fileName: "data/xml/Max Richter - The Departure The Leftovers score.musicxml"},
  {name:"May I See U Again", fileName: "data/xml/May I See U Again.musicxml"},
  {name:"Mendelssohn - Venetian Gondola Song No. 6 op. 19", fileName: "data/xml/Mendelssohn - Venetian Gondola Song No. 6 op. 19.musicxml"},
  {name:"Metallica - Nothing Else Matters", fileName: "data/xml/Metallica - Nothing Else Matters.musicxml"},
  {name:"Moonlight serenade", fileName: "data/xml/Moonlight serenade.musicxml"},
  {name:"Mozart - Fantasia in D Minor K. 397", fileName: "data/xml/Mozart-Fantasia in D Minor K. 397.musicxml"},
  {name:"Mozart Fantasia in C minor K. 475", fileName: "data/xml/Mozart Fantasia in C minor K. 475.musicxml"},
  {name:"Mozart - Lacrimosaoriginal transcription for piano K. 636", fileName: "data/xml/Mozart - Lacrimosa_original_transcription_for_piano.musicxml"},
  {name:"Mozart - K.265 - 12 Variations of Twinkle Twinkle Little Star", fileName: "data/xml/Mozart - K.265 - 12_Variations_of_Twinkle_Twinkle_Little_Star.musicxml"},
  {name:"Mozart - Piano Concerto No. 20 K.466 1st Mvt", fileName: "data/xml/Mozart - Piano Concerto No. 20 K.466 1st Mvt.musicxml"},
  {name:"Mozart - Piano Concerto 23 in A Adagio solo K. 488", fileName: "data/xml/Mozart K.488_Piano_Concerto_23_in_A_2nd_mov._Adagio_for_piano_solo.musicxml"},
  {name:"Mozart - Piano Sonata No.11 in A major-K.331W", fileName: "data/xml/Mozart - Piano Sonata No.11 in A major-K.331W.musicxml"},
  {name:"Mozart - Piano Sonata No. 11_K. 331 3rd Movement Rondo alla Turca", fileName: "data/xml/Mozart - Piano_Sonata_No._11_K._331_3rd_Movement_Rondo_alla_Turca.musicxml"},
  {name:"Mozart - Sonata 16", fileName: "data/xml/Mozart-Sonata_16.musicxml"},
  {name:"Mozart - Sonata 16 - 2nd", fileName: "data/xml/Mozart-Sonata_16_2nd_movement.musicxml"},
  {name:"Mussorgsky - Bydlo", fileName: "data/xml/Mussorgsky - Bydlo.musicxml"},
  {name:"Mussorgsky - Gnomus", fileName: "data/xml/Mussorgsky - Gnomus.musicxml"},
  {name:"Mussorgsky - Promenade", fileName: "data/xml/Mussorgsky - Promenade.musicxml"},
  {name:"My Heart Will Go On", fileName: "data/xml/My Heart Will Go On.musicxml"},
  {name:"Dominant", fileName: "data/xml/Dominant.musicxml"},
  {name:"My first compose", fileName: "data/xml/My first compose.musicxml"},
  {name:"Myuu - Identity Crisis", fileName: "data/xml/Myuu - Identity Crisis.musicxml"},
  {name:"National Anthem of the USSRRussia", fileName: "data/xml/National_Anthem_of_the_USSRRussia.musicxml"},
  {name:"Nutcracker 14a Pas de Deux Hinci version", fileName: "data/xml/Nutcracker 14a Pas de Deux Hinci version.musicxml"},
  {name:"Nino Rota - The Godfather", fileName: "data/xml/Nino Rota - The Godfather.musicxml"},
  {name:"Nino Rota - The Godfather C minor", fileName: "data/xml/Nino Rota - The Godfather C minor.musicxml"},
  {name:"Ode to Joy", fileName: "data/xml/Ode to Joy.musicxml"},
  {name:"Paganini 24 Caprice", fileName: "data/xml/Paganini 24 Caprice.musicxml"},
  {name:"Paul Mauriat - Toccata", fileName: "data/xml/Paul Mauriat - Toccata.musicxml"},
  {name:"Philip Glass - Walk to school", fileName: "data/xml/Philip Glass - Walk to school.musicxml"},
  {name:"Prelude in G Minor Op. 23 No. 5", fileName: "data/xml/Prelude_in_G_Minor_Op._23_No._5.musicxml"},
  {name:"Primavera", fileName: "data/xml/primavera.musicxml"},
  {name:"Rachmaninoff - ex1", fileName: "data/xml/Rachmaninoff - ex1.musicxml"},
  {name:"Rachmaninoff - Flight of the Bumblebee", fileName: "data/xml/Rachmaninoff - Flight of the Bumblebee - N. Rimsky-Korsakov.musicxml"},
  {name:"Rachmaninoff - op.10 - 6 Romance", fileName: "data/xml/Rachmaninoff - op.10 - 6 Romance.musicxml"},
  {name:"Rachmaninoff - Piano Concerto No. 2 Op. 18", fileName: "data/xml/Rachmaninoff_-_Piano_Concerto_No._2_Op._18.musicxml"},
  {name:"Rachmaninoff - Elegie Opus 3 No. 1", fileName: "data/xml/Rachmaninoff - Elegie Opus 3 No. 1.musicxml"},
  {name:"Rachmaninoff - Preludes Op. 32 No. 12 in G-sharp minor", fileName: "data/xml/Rachmaninoff - Preludes Op. 32 No. 12 in G-sharp minor.musicxml"},
  {name:"Rachmaninoff - Prelude in C-sharp Minor Opus 3 No. 2", fileName: "data/xml/Rachmaninoff - Prelude in C-sharp Minor Opus 3 No. 2.musicxml"},
  {name:"Radiohead - Creep", fileName: "data/xml/Radiohead - Creep.musicxml"},
  {name:"Re major arpeggio", fileName: "data/xml/Re major arpeggio.musicxml"},
  {name:"River Flows in You", fileName: "data/xml/River_Flows_in_You.musicxml"},
  {name:"Rob Dougan - Clubbed to Death", fileName: "data/xml/Rob Dougan - Clubbed to Death.musicxml"},
  {name:"Sarabande", fileName: "data/xml/Sarabande_de_Haendel.musicxml"},
  {name:"Scale D Major diverge", fileName: "data/xml/Scale D Major diverge.musicxml"},
  {name:"Schubert Ellens Gesang III D. 839 Gb major", fileName: "data/xml/Schubert_Ellens Gesang III D.839.musicxml"},
  {name:"Schubert Impromptu No. 3 Op. 90 D. 899 Gb major", fileName: "data/xml/Schubert_Impromptu_No._3_Op._90_D_899_G_Majeur_Transcription_de_Liszt.musicxml"},
  {name:"Schubert Moments Musicaux D. 780 No. 3 in F Minor", fileName: "data/xml/Schubert - Moments_Musicaux_D._780_No._3_in_F_Minor.musicxml"},
  {name:"Schubert Serenade - Standchen - Arr. By Lizst D 957 №4", fileName: "data/xml/Schubert Serenade - Standchen - Arr. By Lizst D 957 №4.musicxml"},
  {name:"Schumann - Kinderszenen - No.7 Op.15 - Dreaming Trumerei", fileName: "data/xml/Schumann - Kinderszenen - No.7 Op.15 - Dreaming Trumerei.musicxml"},
  {name:"Schumann - Toccata_Op. 7 Piano solo", fileName: "data/xml/Schumann_Toccata_Op._7_Piano_solo.musicxml"},
  {name:"Schumann - The Wild Horseman Op. 68 No. 8", fileName: "data/xml/Schumann - The Wild Horseman Op. 68 No. 8.musicxml"},
  {name:"Schumann - Symphonic Etudes Op.13 Etude I Var. 1", fileName: "data/xml/Schumann - Symphonic Etudes Op.13 Etude I Var. 1.musicxml"},
  {name:"Secret Garden - Song From a Secret Garden", fileName: "data/xml/Secret Garden - Song From a Secret Garden.musicxml"},
  {name:"Shmitz-21", fileName: "data/xml/shmitz-21.musicxml"},
  {name:"Sibelius Jean - Etude op. 76 n.2", fileName: "data/xml/Sibelius Jean - Etude op. 76 n.2.musicxml"},
  {name:"Sorry Seems To Be The Hardest Word", fileName: "data/xml/Sorry Seems To Be The Hardest Word.musicxml"},
  {name:"Strauss - Also Sprach Zarathustra", fileName: "data/xml/Also Sprach Zarathustra.musicxml"},
  {name:"Strauss Johann Jr. - On the Beautiful Blue Danube Piano solo", fileName: "data/xml/Strauss Johann Jr. - On the Beautiful Blue Danube Piano solo.musicxml"},
  {name:"SYML - I wanted to Leave", fileName: "data/xml/SYML - I wanted to Leave.musicxml"},
  {name:"SYML - Mr. Sandman", fileName: "data/xml/SYML - Mr._Sandman.musicxml"},
  {name:"Tchaikovsky - Dance Of the Sugar Plum Fairy (Nohpets Transcribsion)", fileName: "data/xml/Tchaikovsky - Dance Of the Sugar Plum Fairy (Nohpets Transcribsion).musicxml" },
  {name:"Tchaikovsky - Op. 37 no. 3 March Song of the Lark", fileName: "data/xml/Tchaikovsky - Op. 37 no. 3 March Song of the Lark.musicxml"},
  {name:"Tchaikovskys - October Autumn Song", fileName: "data/xml/Tchaikovskys - October Autumn Song.musicxml"},
  {name:"Tchaikovsky - Piano Concerto No 1", fileName: "data/xml/Tchaikovsky - Piano Concerto No 1.musicxml"},
  {name:"The Clowns", fileName: "data/xml/The_Clowns.musicxml"},
  {name:"The Daydream - Tears", fileName: "data/xml/The Daydream - Tears.musicxml"},
  // {name:"The Daydream - Tears B minor", fileName: "data/xml/The Daydream - Tears B minor.musicxml"},
  {name:"The Entertainer", fileName: "data/xml/The Entertainer.musicxml"},
  {name:"The Pink Panther Theme", fileName: "data/xml/The pink panther theme.musicxml"},
  {name:"The Sound Of Silence", fileName: "data/xml/The Sound Of Silence.musicxml"},
  {name:"Umberto Tozzi - Ti Amo Piano from La Casa de Papel", fileName: "data/xml/Umberto Tozzi - Ti Amo Piano from La Casa de Papel.musicxml"},
  {name:"Una Mattina", fileName: "data/xml/Una Mattina.musicxml"},
  // {name:"Vivaldi Four Seasons Winter", fileName: "data/xml/Vivaldi Four Seasons Winter First movement in F minor.musicxml"},
  {name:"Vivaldi Violin Concerto in E major Op. 8 No. 1 RV. 269 Spring for Solo Piano", fileName: "data/xml/Vivaldi_-_Violin_Concerto_in_E_major_Op._8_No._1_RV._269_Spring_for_Solo_Piano.musicxml"},
  {name:"Vivaldi Violin Concerto in F minor Op. 8 No. 4 RV. 297 Winter for Solo Piano", fileName: "data/xml/Vivaldi Violin Concerto in F minor Op. 8 No. 4 RV. 297 Winter for Solo Piano.musicxml"},
  {name:"We are the Champion", fileName: "data/xml/We_are_the_Champion.musicxml"},
  {name:"Woodsman - Dream River", fileName: "data/xml/Woodsman - Dream River.musicxml"},
  {name:"Yann Tiersen - Comptine Dun Autre Ete Lapres", fileName: "data/xml/Yann Tiersen - Comptine Dun Autre Ete Lapres.musicxml"},
  {name:"Yehezkel Raz - Behind every decision", fileName: "data/xml/Yehezkel Raz - Behind every decision.musicxml"},
  {name:"Yesterday", fileName: "data/xml/Yesterday.musicxml"},
  {name:"В лесу родилась Ёлочка", fileName: "data/xml/В лесу родилась Ёлочка.musicxml"},
  {name:"Воспоминание", fileName: "data/xml/Воспоминание.musicxml"},
  {name:"Глинка - Двухголосная Фуга", fileName: "data/xml/Глинка - Двухголосная Фуга.musicxml"},
  {name:"Глиэр - Прелюдия Соч 43-1", fileName: "data/xml/Глиэр - Прелюдия Соч 43-1.musicxml"},
  {name:"Деак - Ну погоди", fileName: "data/xml/Деак - Ну погоди.musicxml"},
  {name:"Десятников - Из жизни Кощея", fileName: "data/xml/Десятников - Из жизни Кощея.musicxml"},
  {name:"Добрый жук", fileName: "data/xml/Добрый жук.musicxml"},
  {name:"Кабалевский - Кавалерийская", fileName: "data/xml/Кабалевский - Кавалерийская.musicxml"},
  {name:"Кобылянский - Этюд 7", fileName: "data/xml/Кобылянский - Этюд 7.musicxml"},
  {name:"Крылатые качели", fileName: "data/xml/Крылатые качели.musicxml"},
  {name:"Майкапар - Дождик", fileName: "data/xml/Майкапар - Дождик.musicxml"},
  {name:"Мой ласковый и нежный зверь", fileName: "data/xml/Мой ласковый и нежный зверь.musicxml"},
  {name:"Оттепель - аранжировка Александр Лосев", fileName: "data/xml/Оттепель - аранжировка Александр Лосев.musicxml"},
  {name:"Подмосковные вечера обработка Клиберна", fileName: "data/xml/Подмосковные вечера обработка Клиберна.musicxml"},
  {name:"Прокофьев - Сказочка Op. 65 - 3", fileName: "data/xml/Прокофьев - Сказочка Op. 65 - 3.musicxml"},
  {name:"Прокофьев - Соната 6", fileName: "data/xml/Прокофьев - Piano Sonata No.6 Op.82.musicxml"},
  {name:"Скрябин op. 8 - No 12 in D Minor", fileName: "data/xml/Скрябин op. 8 - No 12 in D Minor.musicxml"},
  {name:"Скрябин op. 11 - No 10 C sharp minor", fileName: "data/xml/Скрябин op. 11 - No 10 C sharp minor.musicxml"},
  {name:"Скрябин op. 42 - No 8 F sharp major", fileName: "data/xml/Скрябин op. 42 - No 8 F sharp major.musicxml"},
  {name:"Танкист", fileName: "data/xml/Танкист.musicxml"},
  {name:"Чайковский - Лебединное озеро", fileName: "data/xml/Tchaikovsky - Swan Lake.musicxml"},
  {name:"Чайковский - Танец феи драже (Плетнёв)", fileName: "data/xml/Чайковский - Танец феи драже (Плетнёв).musicxml"},
  {name:"Чайковский П. И. Op. 39 Детский альбом. VI. Болезнь куклы", fileName: "data/xml/Tchaikovsky_Op._39_Childrens_Album_-_P._I._VI. Болезнь куклы.musicxml" },
  {name:"Чайковский П. И. Op. 39 Детский альбом. VII. Похороны куклы", fileName: "data/xml/Tchaikovsky_Op._39_Childrens_Album_-_P._I._VII. Похороны куклы.musicxml" },
  {name:"Чайковский П. И. Op. 39 Детский альбом. IX. Новая кукла", fileName: "data/xml/Tchaikovsky_Op._39_Childrens_Album_-_P._I._IX. Новая кукла.musicxml" },
  {name:"Чайковский П. И. Op. 39 Детский альбом. XVI. Стариная француская песенка", fileName: "data/xml/Tchaikovsky_Op._39_Childrens_Album_-_P._I._XVI. Стариная француская песенка.musicxml" },
  {name:"Чайковский П. И. Op. 39 Детский альбом. XVIII. Неаполитанская песенка", fileName: "data/xml/Tchaikovsky_Op._39_Childrens_Album_-_P._I._XVIII. Неаполитанская песенка.musicxml" },
  {name:"Чюрлёнис - Море", fileName: "data/xml/Чюрлёнис - Море.musicxml"},
  {name:"Шостакович - Вальс №2", fileName: "data/xml/Shostakovich_Waltz_No._2.musicxml"},
  {name:"Шостакович - Вальс №2 (D minor)", fileName: "data/xml/Shostakovich_Waltz_No._2-D minor.musicxml"},
  {name:"Шостакович - Концерт для фортепиано №2 II Andante", fileName: "data/xml/Shostakovich - Piano_Concerto_No._2_in_F_Major_Op._102_II._Andante.musicxml"},
  {name:"Шостакович - Op. 87 Прелюдия IV", fileName: "data/xml/Шостакович - Прелюдия IV. Окончательный.musicxml"},
  {name:"Щедрин - Юмореска", fileName: "data/xml/Shchedrin Rodion - Humoresque.musicxml"},
  // {name:"Диалог", fileName: "data/xml/Диалог.musicxml"},
  // {name:"Колыбельная", fileName: "data/xml/Колыбельная.musicxml"},
  // {name:"Миллион Алых Роз", fileName: "data/xml/Миллион Алых Роз.musicxml"},
  // {name:"Песенка про кузнечика", fileName: "data/xml/Песенка про кузнечика.xml"}
  ];
