export const MusicFiles = [ {name:"Test", fileName: "data/xml/test.musicxml"},
  {name:"Arpeggio D major", fileName: "data/xml/Arpeggio D major.musicxml"},
  {name:"Arpeggio D minor", fileName: "data/xml/Arpeggio D minor.musicxml"},
  {name:"Arpeggio D minor broken", fileName: "data/xml/Arpeggio D minor broken.musicxml"},
  {name:"Arpeggio F major", fileName: "data/xml/Arpeggio F major.musicxml"},
  {name:"Arpeggio F major - octave", fileName: "data/xml/Arpeggio F major - octave.musicxml"},
  {name:"Arpeggio F major - octave + 3th", fileName: "data/xml/Arpeggio F major - octave + 3th.musicxml"},
  {name:"Arpeggio H minor", fileName: "data/xml/Arpeggio H minor.musicxml"},
  {name:"Bach G Minor arranged Luo Ni", fileName: "data/xml/Bach G Minor arranged Luo Ni.musicxml"},
  {name:"Beethoven Bagatelle No. 25 in A minor", fileName: "data/xml/Beethoven Bagatelle No. 25 in A minor.musicxml"},
  {name:"Blue dabune", fileName: "data/xml/Blue dabune.xml"},
  {name:"Beethoven Ode to Joy", fileName: "data/xml/Beethoven - Ode to Joy.musicxml"},
  {name:"Beethoven Sonata No. 8 Op. 13 Pathetique", fileName: "data/xml/Beethoven Sonata No. 8 Op. 13 Pathetique.musicxml"},
  {name:"Beethoven Sonata No. 8 Op. 13 Pathetique - Second Ab major", fileName: "data/xml/Beethoven Sonata No. 8 Op. 13 Pathetique - Second Ab major.musicxml"},
  {name:"Beethoven Sonata No. 8 Op. 13 Pathetique III Rondo", fileName: "data/xml/Beethoven Sonata No. 8 Op. 13 Pathetique III Rondo.musicxml"},
  {name:"Beethoven Sonata 14 C# Minor", fileName: "data/xml/Beethoven Sonata 14 C Sharp Minor.musicxml"},
  {name:"Beethoven Sonata 14 C# Minor 3rd Movemen", fileName: "data/xml/Beethoven Sonata 14 C Sharp Minor 3rd Movemen.musicxml"},
  {name:"Beethoven Sonate 17 Tempest 3rd Movement", fileName: "data/xml/Beethoven Sonate No. 17 Tempest 3rd Movement.musicxml"},
  {name:"Beethoven Sonata 21 Op. 53", fileName: "data/xml/Beethoven Piano_Sonata_No.21_Op.53.musicxml"},
  {name:"Beethoven Symphony No. 5 1 st movement Piano solo", fileName: "data/xml/Beethoven Symphony No. 5 1 st movement Piano solo.musicxml"},
  {name:"Brahms Op. 35 Variations on a Theme Paganini", fileName: "data/xml/Brahms Op. 35 Variations on a Theme Paganini.musicxml"},
  {name:"Burgmuller - Op.100 - Arabesque", fileName: "data/xml/Burgmuller - Op.100 - Arabesque.musicxml"},
  // {name:"Beethoven Op. 53", fileName: "data/xml/Beethoven-Op._53.xml"},
  // {name:"BWV Praeambulum in F Major", fileName: "data/xml/BWV Praeambulum in F Major.xml"},
  {name:"BWV 528 Organ Sonata No4 2. Andante", fileName: "data/xml/BWV 528_Organ_Sonata_No._4_-_2._Andante_Adagio_-_Vikingur_Olafsson_Interpretation.musicxml"},
  {name:"BWV 565", fileName: "data/xml/BWV-565.musicxml"},
  {name:"BWV 565 second part", fileName: "data/xml/BWV 565 second part.musicxml"},
  {name:"BWV 565 exercise", fileName: "data/xml/BWV-565 exercise.musicxml"},
  {name:"BWV 578 - Bach Fugue in G Minor", fileName: "data/xml/BWV 578 - Bach Fugue in G Minor Piano solo.musicxml"},
  {name:"BWV 772 J. S. Bach Inventio 1", fileName: "data/xml/BWV 772 J._S._Bach_Invention_Nr._1.musicxml"},
  {name:"BWV 773 J. S. Bach Inventio 2", fileName: "data/xml/BWV 773 J.S.Bach_Inventio_2.musicxml"},
  {name:"BWV 846 Prelude C Major", fileName: "data/xml/BWV 846 Prelude C Major.xml"},
  // {name:"BWV 846 Harmony", fileName: "data/xml/BWV-846-Harmony.xml"},
  {name:"BWV 847 Prelude C Minor", fileName: "data/xml/BWV 847 Prelude C Minor.musicxml"},
  {name:"BWV 847 ex001", fileName: "data/xml/BWV 847 ex001.musicxml"},
  {name:"BWV 853 Prelude N8 in E Flat Minor", fileName: "data/xml/BWV 853 Prelude N8 in E Flat Minor.musicxml"},
  // {name:"B Major", fileName: "data/xml/B major.musicxml"},
  // {name:"BWV 855 Prelude E Minor", fileName: "data/xml/BWV-855_in_E_Minor.musicxml"},
  // {name:"BWV-847 C minor Harmony", fileName: "data/xml/BWV-847 C minor Harmony.musicxml"},
  // {name:"BWV-847 Harmony", fileName: "data/xml/BWV-847_Harmony.musicxml"},
  // {name:"By the Seaside", fileName: "data/xml/By the Seaside.musicxml"},
  // {name:"C major double time II", fileName: "data/xml/C major double time II.musicxml"},
  // {name:"C major double time", fileName: "data/xml/C major double time.musicxml"},
  // {name:"Cherny Op. 453-3", fileName: "data/xml/Cherny-Op._453-3.xml"},
  // {name:"Cherny Op. 453-4", fileName: "data/xml/Cherny-Op._453-4.xml"},
  // {name:"Cherny Op. 453-5", fileName: "data/xml/Cherny-Op._453-5.xml"},
  // {name:"Cherny Op. 453-6", fileName: "data/xml/Cherny-Op._453-6.xml"},
  // {name:"Cherny Op. 453-6-left", fileName: "data/xml/Cherny-Op._453-6-left.xml"},
  // {name:"Cherny Op. 453-7", fileName: "data/xml/Cherny-Op._453-7.xml"},
  // {name:"Cherny Op. 453-8", fileName: "data/xml/Cherny-Op._453-8.xml"},
  // {name:"Cherny Op. 453-9", fileName: "data/xml/Cherny-Op._453-9.xml"},
  // {name:"Cherny-17", fileName: "data/xml/Cherny-17.musicxml"},
  // {name:"D 935 Ab Major", fileName: "data/xml/D 935 Importu.musicxml"},
  // {name:"Gliere 43 №1", fileName: "data/xml/Gliere 43 №1.musicxml"},
  // {name:"Heller Sailor's Song", fileName: "data/xml/Heller - Sailor's Song op.musicxml"},
  {name:"A dur", fileName: "data/xml/A dur.musicxml"},
  // {name:"BWV 1068 - Air on the G String", fileName: "data/xml/BWV 1068 - Air on the G String.musicxml"},
  {name:"BWV 1068 - Air on the G String", fileName: "data/xml/BWV 1068 J._S._Bach_-_Air_on_the_G_String_Piano_arrangement.musicxml"},
  {name:"BWV 847 Fugue in C Minor", fileName: "data/xml/BWV 847 Fugue in C Minor.musicxml"},
  {name:"BWV 848 Prelude C# Major", fileName: "data/xml/BWV 848 Prelude C Major.musicxml"},
  {name:"BWV 849 Fugue C# Minor", fileName: "data/xml/BWV 849 Fugue C Minor.musicxml"},
  {name:"BWV 849 Prelude C# Minor", fileName: "data/xml/BWV 849 Prelude C sharp Minor.musicxml"},
  {name:"BWV 851 Prelude D Minor", fileName: "data/xml/BWV 851 Prelude D Minor.musicxml"},
  {name:"BWV 851 Prelude D Minor", fileName: "data/xml/BWV 855 Prelude No. 10 in E Minor.musicxml"},
  {name:"BWV 855a Prelude B minor arr Siloti", fileName: "data/xml/BWV 855a Prelude_in_B_minor_arr._by_A_Siloti.musicxml"},
  {name:"BWV 858 Prelude F-sharp Major", fileName: "data/xml/BWV-858_Prelude_F_sharp_Major.xml"},
  {name:"BWV 927 (Twelve Little Preludes)", fileName: "data/xml/BWV 927.musicxml"},
  {name:"BWV 999 Little Preambule C Minor", fileName: "data/xml/BWV-999 Little Preambule C Minor.musicxml"},
  {name:"Canon D dur full", fileName: "data/xml/Canon_in_D_full.musicxml"},
  {name:"Canon D dur", fileName: "data/xml/Canon D dur.musicxml"},
  {name:"Cherny Op. 453-1", fileName: "data/xml/Cherny-Op._453-1.xml"},
  {name:"Cherny Op. 453-2", fileName: "data/xml/Cherny-Op._453-2.xml"},
  {name:"Chopin - Drei Walzer Op. 64 No. 2", fileName: "data/xml/Chopin Drei Walzer Op. 64 No. 2.musicxml"},
  {name:"Chopin - Fantaisie-Impromptu", fileName: "data/xml/Chopin - Fantaisie-Impromptu.musicxml"},
  {name:"Chopin - Nocturne in B-Flat minor, Op. 9, No. 1 ", fileName: "data/xml/Chopin_-_Nocturne_Op_9_No_1_B_Flat_Minor.musicxml"},
  {name:"Chopin - Nocturne in E-flat major, Op. 9, No. 2", fileName: "data/xml/Chopin_Nocture_opus_9_number2.musicxml"},
  {name:"Chopin - Sonata No.2 in B-flat minor", fileName: "data/xml/Chopin Sonata_No.2_in_B-flat_minor.musicxml"},
  {name:"Chopin 10-2 ex1", fileName: "data/xml/Chopin 10-2-ex1.musicxml"},
  {name:"Chopin 10-2 in A Minor", fileName: "data/xml/Chopin 10-2.musicxml"},
  {name:"Chopin 28-4 in E Minor", fileName: "data/xml/Prelude_Opus_28_No._4_in_E_Minor.musicxml"},
  {name:"Chopin 28-20 in C Minor", fileName: "data/xml/Chopin 28-20 in C Minor.musicxml"},
  {name:"Chromatic - exercise", fileName: "data/xml/Chromatic - exercise.musicxml"},
  {name:"Chromatic Scale", fileName: "data/xml/Chromatic Scale.musicxml"},
  {name:"Czerny - Op.139 - 001", fileName: "data/xml/Czerny- Op.139 - 001.musicxml"},
  {name:"Czerny - Op.139 - 002", fileName: "data/xml/Czerny- Op.139 - 002.musicxml"},
  {name:"Czerny - Op.139 - 003", fileName: "data/xml/Czerny- Op.139 - 003.musicxml"},
  {name:"Czerny - Op.139 - 004", fileName: "data/xml/Czerny- Op.139 - 004.musicxml"},
  {name:"Czerny - Op.139 - 005", fileName: "data/xml/Czerny- Op.139 - 005.musicxml"},
  {name:"Czerny - Op.139 - 006", fileName: "data/xml/Czerny- Op.139 - 006.musicxml"},
  {name:"Czerny - Op.139 - 007", fileName: "data/xml/Czerny- Op.139 - 007.musicxml"},
  {name:"Czerny - Op.139 - 008", fileName: "data/xml/Czerny- Op.139 - 008.musicxml"},
  {name:"Czerny - Op.139 - 009", fileName: "data/xml/Czerny- Op.139 - 009.musicxml"},
  {name:"Czerny - Op.139 - 010", fileName: "data/xml/Czerny- Op.139 - 010.musicxml"},
  {name:"Czerny - Op.139 - 011", fileName: "data/xml/Czerny- Op.139 - 011.musicxml"},
  {name:"Czerny - Op.139 - 012", fileName: "data/xml/Czerny- Op.139 - 012.musicxml"},
  {name:"Czerny - Op.139 - 013", fileName: "data/xml/Czerny- Op.139 - 013.musicxml"},
  {name:"Czerny - Op.139 - 014", fileName: "data/xml/Czerny- Op.139 - 014.musicxml"},
  {name:"Czerny - Op.139 - 015", fileName: "data/xml/Czerny- Op.139 - 015.musicxml"},
  {name:"Czerny - Op.139 - 016", fileName: "data/xml/Czerny- Op.139 - 016.musicxml"},
  {name:"Czerny - Op.139 - 017", fileName: "data/xml/Czerny- Op.139 - 017.musicxml"},
  {name:"Czerny - Op.139 - 018", fileName: "data/xml/Czerny- Op.139 - 018.musicxml"},
  {name:"Czerny - Op.139 - 019", fileName: "data/xml/Czerny- Op.139 - 019.musicxml"},
  {name:"Czerny - Op.139 - 020", fileName: "data/xml/Czerny- Op.139 - 020.musicxml"},
  {name:"Czerny - Op.139 - 021", fileName: "data/xml/Czerny- Op.139 - 021.musicxml"},
  {name:"Czerny - Op.139 - 022", fileName: "data/xml/Czerny- Op.139 - 022.musicxml"},
  {name:"Czerny - Germer-19", fileName: "data/xml/Czerny-Germer-19.musicxml"},
  {name:"D dur 4 octave", fileName: "data/xml/D dur.musicxml"},
  {name:"Dance of the Knights", fileName: "data/xml/Dance_of_the_Knights_Transcription_for_solo_piano.musicxml"},
  {name:"Debussy - Clair de Lune Suite Bergamasque No. 3", fileName: "data/xml/Debussy - Clair de Lune Suite Bergamasque No. 3.musicxml"},
  {name:"Domenico Scarlatti K.466", fileName: "data/xml/Domenico Scarlatti K.466.musicxml"},
  {name:"ex001", fileName: "data/xml/ex001.musicxml"},
  {name:"Ennio Morricone - Chi Mai", fileName: "data/xml/Ennio Morricone - Chi Mai.musicxml"},
  {name:"F dur", fileName: "data/xml/F dur.musicxml"},
  {name:"F Major diverge", fileName: "data/xml/F Major diverge.musicxml"},
  {name:"Faure - Sicilienne", fileName: "data/xml/Faure - Sicilienne.musicxml"},
  {name:"For the Damaged Coda", fileName: "data/xml/Evil_Morty_Theme_For_the_Damaged_Coda_Solo_Piano.musicxml"},
  {name:"G dur octave", fileName: "data/xml/G dur octave.musicxml"},
  {name:"G minor octave hand separate", fileName: "data/xml/G dur octave hand separate.musicxml"},
  {name:"Game of Thrones", fileName: "data/xml/Game_of_Thrones_Main_Theme.musicxml"},
  {name:"Grieg - Piano Concerto in A minor - 1st movement", fileName: "data/xml/Grieg_-_Piano_Concerto_in_A_minor_-_1st_movement_-_Piano_Solo.musicxml"},
  {name:"Grieg In The Hall Of The Mountain King", fileName: "data/xml/Grieg In The Hall Of The Mountain King.musicxml"},
  {name:"Gymnopedie", fileName: "data/xml/Gymnopedie.musicxml"},
  {name:"Gnossienne No 1", fileName: "data/xml/Gnossienne_No._1.musicxml"},
  {name:"Handel - Passacaglia", fileName: "data/xml/Handel - Passacaglia.musicxml"},
  {name:"Handel - Suite no.7 HWV 432", fileName: "data/xml/Handel - Passacaglia_from_Suite_no.7_HWV_432_-_Georg_Frideric.musicxml"},
  {name:"Hanon - Ex 1", fileName: "data/xml/Hanon - Ex 1.musicxml"},
  {name:"Hanon - Ex 6", fileName: "data/xml/Hanon - Ex 6.musicxml"},
  {name:"Hanz Zimmer - Mountains", fileName: "data/xml/Hanz Zimmer - Mountains.musicxml"},
  {name:"Heller - Opus 45 no 15 D minor", fileName: "data/xml/Etude_No._15_in_D_Minor_Opus_45_No._15_Heller.musicxml"},
  {name:"Heller exercise 1 ", fileName: "data/xml/Heller-exercise-1.musicxml"},
  {name:"Ilya Beshelvi - Wind", fileName: "data/xml/Ilya Beshelvi - Wind.musicxml"},
  {name:"Jingle Bells", fileName: "data/xml/Jingle_Bells.musicxml"},
  {name:"John Towner Williams - Hedwig's theme", fileName: "data/xml/John Towner Williams - Hedwig's theme.musicxml"},
  {name:"La Candeur", fileName: "data/xml/La Candeur.musicxml"},
  {name:"LE COUCOU by DAQUIN The Cuckoo", fileName: "data/xml/LE_COUCOU_by_DAQUIN_The_Cuckoo.musicxml"},
  {name:"Liszt - Etude in G Minor La Campanella S. 1413", fileName: "data/xml/Liszt - Etude_in_G_Minor_La_Campanella_S._1413-cuted.musicxml"},
  {name:"Love Theme from Flashdance", fileName: "data/xml/Love_Theme_from_Flashdance.musicxml"},
  {name:"Lucifer - Creep", fileName: "data/xml/Lucifer - Creep.musicxml"},
  {name:"Ludovico Einaudi - Dietro Casa", fileName: "data/xml/Ludovico Einaudi - Dietro Casa.musicxml"},
  {name:"Ludovico Einaudi - Fly", fileName: "data/xml/Einaudi - Fly.musicxml"},
  {name:"Maksim Mrvica - Croatian Rhapsody", fileName: "data/xml/Maksim Mrvica - Croatian Rhapsody.musicxml"},
  {name:"Moonlight serenade", fileName: "data/xml/Moonlight serenade.musicxml"},
  {name:"Mozart - Sonata 16", fileName: "data/xml/Mozart-Sonata_16.musicxml"},
  // {name:"Sarabande v2", fileName: "data/xml/Sarabande_de_Haendel - variation 2.musicxml"},
  {name:"Sarabande", fileName: "data/xml/Sarabande_de_Haendel.musicxml"},
  // {name:"This Love", fileName: "data/xml/This Love.musicxml"},
  // {name:"Вариация Баха", fileName: "data/xml/Вариация Баха.musicxml"}, //Little Preambule C Major
  {name:"Mozart - Fantasia in D Minor K. 397", fileName: "data/xml/Mozart-Fantasia in D Minor K. 397.musicxml"},
  {name:"Mozart - Lacrimosaoriginal transcription for piano K. 636", fileName: "data/xml/Mozart - Lacrimosa_original_transcription_for_piano.musicxml"},
  {name:"Mozart - Piano Concerto 23 in A Adagio solo K. 488", fileName: "data/xml/Mozart K.488_Piano_Concerto_23_in_A_2nd_mov._Adagio_for_piano_solo.musicxml"},
  {name:"Myuu - Identity Crisis", fileName: "data/xml/Myuu - Identity Crisis.musicxml"},
  {name:"National Anthem of the USSRRussia", fileName: "data/xml/National_Anthem_of_the_USSRRussia.musicxml"},
  {name:"Ode to Joy", fileName: "data/xml/Ode to Joy.musicxml"},
  {name:"Paganini 24 Caprice", fileName: "data/xml/Paganini 24 Caprice.musicxml"},
  {name:"Philip Glass - Walk to school", fileName: "data/xml/Philip Glass - Walk to school.musicxml"},
  {name:"Paul Mauriat - Toccata", fileName: "data/xml/Paul Mauriat - Toccata.musicxml"},
  {name:"Prelude in G Minor Op. 23 No. 5", fileName: "data/xml/Prelude_in_G_Minor_Op._23_No._5.musicxml"},
  {name:"Primavera", fileName: "data/xml/primavera.musicxml"},
  {name:"Re major arpeggio", fileName: "data/xml/Re major arpeggio.musicxml"},
  {name:"Rachmaninoff - ex1", fileName: "data/xml/Rachmaninoff - ex1.musicxml"},
  {name:"Rachmaninoff - Piano Concerto No. 2 Op. 18", fileName: "data/xml/Rachmaninoff_-_Piano_Concerto_No._2_Op._18.musicxml"},
  {name:"Radiohead - Creep", fileName: "data/xml/Radiohead - Creep.musicxml"},
  {name:"River Flows in You", fileName: "data/xml/River_Flows_in_You.musicxml"},
  {name:"Strauss - Also Sprach Zarathustra", fileName: "data/xml/Also Sprach Zarathustra.musicxml"},
  {name:"Schubert Impromptu No. 3 Op. 90 D. 899 Gb major", fileName: "data/xml/Schubert_Impromptu_No._3_Op._90_D_899_G_Majeur_Transcription_de_Liszt.musicxml"},
  {name:"Schubert Ellens Gesang III D. 839 Gb major", fileName: "data/xml/Schubert_Ellens Gesang III D.839.musicxml"},
  {name:"Schubert Moments Musicaux D. 780 No. 3 in F Minor", fileName: "data/xml/Schubert - Moments_Musicaux_D._780_No._3_in_F_Minor.musicxml"},
  {name:"Shmitz-21", fileName: "data/xml/shmitz-21.musicxml"},
  {name:"SYML - I wanted to Leave", fileName: "data/xml/SYML - I wanted to Leave.musicxml"},
  {name:"SYML - Mr. Sandman", fileName: "data/xml/SYML - Mr._Sandman.musicxml"},
  {name:"Schumann - Toccata_Op. 7 Piano solo", fileName: "data/xml/Schumann_Toccata_Op._7_Piano_solo.musicxml"},
  {name:"Sorry Seems To Be The Hardest Word", fileName: "data/xml/Sorry Seems To Be The Hardest Word.musicxml"},
  {name:"Tchaikovsky - Dance Of the Sugar Plum Fairy (Nohpets Transcribsion)", fileName: "data/xml/Tchaikovsky - Dance Of the Sugar Plum Fairy (Nohpets Transcribsion).musicxml" },
  {name:"Tchaikovsky - Piano Concerto No 1", fileName: "data/xml/Tchaikovsky - Piano Concerto No 1.musicxml"},
  {name:"The Clowns", fileName: "data/xml/The_Clowns.musicxml"},
  {name:"The Daydream - Tears", fileName: "data/xml/The Daydream - Tears.musicxml"},
  {name:"The Daydream - Tears B minor", fileName: "data/xml/The Daydream - Tears B minor.musicxml"},
  {name:"The Entertainer", fileName: "data/xml/The Entertainer.musicxml"},
  {name:"The Pink Panther Theme", fileName: "data/xml/The pink panther theme.musicxml"},
  {name:"The Sound Of Silence", fileName: "data/xml/The Sound Of Silence.musicxml"},
  {name:"Una Mattina", fileName: "data/xml/Una Mattina.musicxml"},
  // {name:"Vivaldi Four Seasons Winter", fileName: "data/xml/Vivaldi Four Seasons Winter First movement in F minor.musicxml"},
  {name:"Vivaldi Violin Concerto in E major Op. 8 No. 1 RV. 269 Spring for Solo Piano", fileName: "data/xml/Vivaldi_-_Violin_Concerto_in_E_major_Op._8_No._1_RV._269_Spring_for_Solo_Piano.musicxml"},
  {name:"Vivaldi Violin Concerto in F minor Op. 8 No. 4 RV. 297 Winter for Solo Piano", fileName: "data/xml/Vivaldi Violin Concerto in F minor Op. 8 No. 4 RV. 297 Winter for Solo Piano.musicxml"},
  {name:"Yann Tiersen - Comptine Dun Autre Ete Lapres", fileName: "data/xml/Yann Tiersen - Comptine Dun Autre Ete Lapres.musicxml"},
  {name:"Yesterday", fileName: "data/xml/Yesterday.musicxml"},
  {name:"В лесу родилась Ёлочка", fileName: "data/xml/В лесу родилась Ёлочка.musicxml"},
  {name:"Воспоминание", fileName: "data/xml/Воспоминание.musicxml"},
  {name:"Глинка - Двухголосная Фуга", fileName: "data/xml/Глинка - Двухголосная Фуга.musicxml"},
  {name:"Добрый жук", fileName: "data/xml/Добрый жук.musicxml"},
  {name:"Кобылянский - Этюд 7", fileName: "data/xml/Кобылянский - Этюд 7.musicxml"},
  {name:"Крылатые качели", fileName: "data/xml/Крылатые качели.musicxml"},
  {name:"Майкапар - Дождик", fileName: "data/xml/Майкапар - Дождик.musicxml"},
  {name:"Мой ласковый и нежный зверь", fileName: "data/xml/Мой ласковый и нежный зверь.musicxml"},
  {name:"Оттепель - аранжировка Александр Лосев", fileName: "data/xml/Оттепель - аранжировка Александр Лосев.musicxml"},
  {name:"Подмосковные вечера обработка Клиберна", fileName: "data/xml/Подмосковные вечера обработка Клиберна.musicxml"},
  {name:"Танкист", fileName: "data/xml/Танкист.musicxml"},
  {name:"Чайковский - Лебединное озеро", fileName: "data/xml/Tchaikovsky - Swan Lake.musicxml"},
  {name:"Чайковский - Танец феи драже (Плетнёв)", fileName: "data/xml/Чайковский - Танец феи драже (Плетнёв).musicxml"},
  {name:"Чайковский П. И. Op. 39 Детский альбом. VI. Болезнь куклы", fileName: "data/xml/Tchaikovsky_Op._39_Childrens_Album_-_P._I._VI. Болезнь куклы.musicxml" },
  {name:"Чайковский П. И. Op. 39 Детский альбом. VII. Похороны куклы", fileName: "data/xml/Tchaikovsky_Op._39_Childrens_Album_-_P._I._VII. Похороны куклы.musicxml" },
  {name:"Чайковский П. И. Op. 39 Детский альбом. IX. Новая кукла", fileName: "data/xml/Tchaikovsky_Op._39_Childrens_Album_-_P._I._IX. Новая кукла.musicxml" },
  {name:"Чюрлёнис - Море", fileName: "data/xml/Чюрлёнис - Море.musicxml"},
  {name:"Шостакович - Вальс №2", fileName: "data/xml/Shostakovich_Waltz_No._2.musicxml"},
  {name:"Шостакович - Вальс №2 (D minor)", fileName: "data/xml/Shostakovich_Waltz_No._2-D minor.musicxml"},
  // {name:"Диалог", fileName: "data/xml/Диалог.musicxml"},
  // {name:"Колыбельная", fileName: "data/xml/Колыбельная.musicxml"},
  // {name:"Миллион Алых Роз", fileName: "data/xml/Миллион Алых Роз.musicxml"},
  // {name:"Песенка про кузнечика", fileName: "data/xml/Песенка про кузнечика.xml"}
  ];

// Settings = {}

// Settings.staff = 0;
// Settings.temp = 40;

// if ('localhost:8080' == location.host) {
//   Ut.loadjs('conf/localSettings.js')
//     .then(() => {
//       console.log('locals loaded');
//     });
// } else {
//   Settings.coach = function (a, m, s) {
//     if (2 == App.setting.coach) {
//       return (new PlayFive(a, m, 'same note'));
//     } else if (3 == App.setting.coach) {
//       return (new PlayFive(a, m, ''));
//     } else if (4 == App.setting.coach) {
//       return (new PlayTriplets(a, m));
//     } else {
//       return (new PlayFaster(a, m, s));
//     }
//   }
// }

// if (undefined == Settings.range) Settings.range = [0, 10000];
